### ISSUE TITLE
OSFileStore.updateAtrributes() always return false on windows

### ISSUE THREAD

**Issue by pacive** [oshi/oshi#1138]
I'm currently working on updating the systeminfo binding in [OpenHAB](https://github.com/openhab), which uses OSHI to get stats on the running system. Previously a lot of the methods created new objects for NetworkIF, OSFileStore and PowerSource, but I am now changing them to use the updateAttributes() methods. This works well for the NetworkIF and PowerSource, and also works for OSFileStore on Linux, but when I run the application on windows OSFileStore.updateAtrributes() returns false and the fields are not updated.

I'm not versed in the internal workings of OSHI, but might be able to assist with debugging if I can get some instructions.

Openhab currently uses OSHI 4.2.1, and I'm running it on Windows 10 Home 1909.

Is this already solved in a later version of OSHI so I just need to update the dependency?

**Comment by dbwiddis** [comment]
This is indeed a bug in the current version.  The update routine tries to match the name with a local filesystem, but OSHI overwrites the name with a more verbose version so it fails.  The WMI query similarly fails because we've combined the description and name fields.   Bottom line: matching on the name field just plain doesn't work!

I'll try to fix this tomorrow.

**Comment by dbwiddis** [comment]
FYI, the location of the bug is in the WindowsFileSystem class.  Both `getLocalVolumes()` and `getWmiVolumes()` take a `nameToMatch` argument that will never match.  The fix would be to find another field to match.  For the local volumes, the volume string is a unique GUID and a good match.  For WMI we need to split up the `nameToMatch` (currently "Foo (bar)") into its components "Foo" (matches description) and "bar" (matches name).

**Comment by pacive** [comment]
Updated my dependency to OSHI 4.5.0, and got some log output at least, not sure if it's related:
```
10:18:59.357 [WARN ] [util.platform.windows.WmiQueryHandler] - COM exception: Invalid Query: SELECT DESCRIPTION,DRIVETYPE,FILESYSTEM,FREESPACE,NAME,PROVIDERNAME,SIZE,VOLUMENAME FROM Win32_LogicalDisk AND Name="Local Fixed Disk (C:)"
```
But glad to hear you know what the problem is. Let me know if I can help with testing!

**Comment by dbwiddis** [comment]
Doh!  Thanks for the log entry. The name match should have worked, but the query is clearly missing a `WHERE`....

**Comment by dbwiddis** [comment]
`where ? " WHERE" : " AND"` should have been `where ? " AND" : " WHERE"`

**Comment by dbwiddis** [comment]
OK, should be working now in SNAPSHOT.  Let me know if there's a time you plan on releasing, so I can cut a new release (but would like to finish tweaking my latest GUI code first).

**Comment by pacive** [comment]
No hurry, I have a workaround in the meantime, take your time and release when you're ready!

**Comment by dbwiddis** [comment]
Cool. I tried to release last night but hit errors with the Javadoc plugin that I was too tired to troubleshoot, so I'll wait.   FYI, the individual updates enabled by this are really only intended for monitoring a single filestore, and are less efficient if you're updating "all" the filestores than just collecting all the filestores a second time and manually updating the results.

**Comment by pacive** [comment]
I got the updates working with the 4.6.0-snapshot, but still get the same log message. Not sure what call is producing it though, but can try to debug some more.
As for your last comment, only one filestore is updated each time currently.

**Comment by dbwiddis** [comment]
I may have pushed a newer snapshot from a branch rather than master, which may not have had the fix installed (and would have broken it again).  I just re-deployed the SNAPSHOT from master, so can you check the latest SNAPSHOT and try again?

If it's still there, is it the identical log message? Can you look to see if there's a WHERE or AND in it?  Is it a local or network drive that's failing?

**Comment by pacive** [comment]
No more log messages, everything seems to work. Thanks for your help!

**Comment by dbwiddis** [comment]
Great. That snapshot will probably become 5.5.1 once I figure out what's broken in the release.
