### ISSUE TITLE
maven-javadoc-plugin 3.2.0 breaks release

### ISSUE THREAD

**Issue by dbwiddis** [oshi/oshi#1145]
I was repeatedly unable to successfully execute `mvn release:perform` with the latest version of the javadoc plugin.  Rolling back to 3.1.1 caused no problems.  I can't see anything obvious about what might have changed and would appreciate the help of someone more experienced in maven trying to troubleshoot this.

It works fine on the `oshi-core` artifact but fails on the shaded version.

Log right before the errors posted below.

```
    Building index for all the packages and classes...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/overview-tree.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/deprecated-list.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/index.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/index-all.html...
    Building index for all classes...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/allclasses-index.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/allpackages-index.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/overview-summary.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/help-doc.html...
    1 error
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary for Operating System and Hardware Information 4.5.1:
    [INFO] 
    [INFO] Operating System and Hardware Information .......... SUCCESS [01:16 min]
    [INFO] oshi-core .......................................... SUCCESS [04:42 min]
    [INFO] oshi-core-shaded ................................... FAILURE [  6.868 s]
    [INFO] oshi-demo .......................................... SKIPPED
    [INFO] oshi-dist .......................................... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time:  06:05 min
    [INFO] Finished at: 2020-03-19T16:40:04-07:00
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (javadoc-jar) on project oshi-core-shaded: MavenReportException: Error while generating Javadoc: 
    [ERROR] Exit code: 1 - javadoc: error - Error reading file: /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/../apidocs/element-list
    [ERROR] 
    [ERROR] Command line was: /usr/local/opt/openjdk/bin/javadoc @options @packages
```

**Comment by dbwiddis** [comment]
Here's a [list of the changes](https://github.com/apache/maven-javadoc-plugin/compare/maven-javadoc-plugin-3.1.1...maven-javadoc-plugin-3.2.0#diff-88f0194461f4bded2781d58f4cb8c9e8).  Perhaps @olamy might have an inkling what to change.

**Comment by dbwiddis** [comment]
The mention of `element-list` implies [this commit](https://github.com/apache/maven-javadoc-plugin/commit/112f5a5ca1639ab9508951663dae3594ecbb0240) may be the problem, but I don't understand what happened...

**Comment by hazendaz** [comment]
Arrggghhh...lots of maven plugins have been having issues lately.  This one in particular has been problematic for me to with newer jdks.  Thanks for heads up on this one.

What jdk version were you using?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by olamy** [comment]
@dbwiddis what jdk are you using? bear in mind jdk11 from oracle are not up2date especially with issues fixed for javadoc... :( better using openjdk. Some IT test with maven plugin are failing with Oracle jdk but not with openjdk....

**Comment by dbwiddis** [comment]
Of interest, running `mvn javadoc:jar` on the command line generates all the lines up to right before the above error, and completes successfully.  When 3.1.1, the search for that `element-list` file is also skipped: 
```
Generating /Users/danielwiddis/git/oshi/oshi-core-shaded/target/apidocs/help-doc.html...
[INFO] Building jar: /Users/danielwiddis/git/oshi/oshi-core-shaded/target/oshi-core-shaded-4.5.1-SNAPSHOT-javadoc.jar
```

Also of interest, even with 3.2.0, during the `mvn release:prepare` cycle, it completes successfully with the same output as 3.1.1.  So the interaction with the release plugin is the issue here, and whatever follows the `javadoc:jar` goal in `release:perform` that's different than `release:prepare` is the problematic point.  I'm wondering if it should be publishing a file somewhere and isn't.

**Comment by dbwiddis** [comment]
(Or, the release plugin's execution in a forked environment.)

**Comment by dbwiddis** [comment]
More interesting stuff.  Poring over the source code, it looks like it's supposed to use `package-list` for my java version and yet the plugin generates an `element-list` (at the location referenced by the error) but not a `package-list`...

**Comment by dbwiddis** [comment]
Potential source of the problem, still not sure what it means...
```
[DEBUG] No maven-compiler-plugin defined in ${build.plugins} or in ${project.build.pluginManagement} for the com.github.oshi:oshi-core-shaded:jar:4.6.0-SNAPSHOT. Added Javadoc API link according the javadoc executable version i.e.: 13.0.2
[DEBUG] Found Java API link: https://docs.oracle.com/en/java/javase/13/docs/api/
[DEBUG] Trying to add links for modules...
[DEBUG] Added Javadoc offline link: https://github.com/oshi/oshi/oshi-core/apidocs for the module: com.github.oshi:oshi-core:jar:4.6.0-SNAPSHOT
[INFO] No previous run data found, generating javadoc.
[DEBUG] /usr/local/opt/openjdk/bin/javadoc @options @packages
```

**Comment by dbwiddis** [comment]
As noted in #1243, `<sourcepath>src/main/java</sourcepath>` (already merged) may fix this, and I'll attempt 3.2.0 with the next release to test.

**Comment by dbwiddis** [comment]
Well, I didn't even get as far as `mvn release:perform`.  It failed on the `release:prepare` step:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project oshi-demo: MavenReportException: Error while generating Javadoc: 
    [ERROR] Exit code: 1 - error: module org.slf4j.simple reads package oshi from both com.github.oshi.demo and com.github.oshi
    [ERROR] error: module org.slf4j.simple reads package oshi.jna.platform.windows from both com.github.oshi.demo and com.github.oshi
    [ERROR] error: module org.slf4j.simple reads package oshi.jna.platform.linux from both com.github.oshi.demo and com.github.oshi
    [ERROR] error: module org.slf4j.simple reads package oshi.jna.platform.unix from both com.github.oshi.demo and com.github.oshi
<and lots more like that>
```
But I haven't declared any modules, just added the "Automatic Module Name".   

If there's an easy fix to this, I'd welcome it, otherwise I'm leaning toward completely removing anything related to Java 9+ until someone who actually needs it submits a PR.

**Comment by hazendaz** [comment]
@dbwiddis There are definitely bugs.  Drop the source on javadocs explicity to 8 if you have not already and just leave it there.  I've released with 3.2.0 without any issues but had to make strange changes like that.  Others have went as far as a few other changes due to the link errors that pop on it.

**Comment by hazendaz** [comment]
Use the <source> option if I'm not mistaken.  Then it will stop trying to use the modular path.

**Comment by dbwiddis** [comment]
I already was using `<sourcepath>`.  Is there an example somewhere?

**Comment by hazendaz** [comment]
http://maven.apache.org/plugins/maven-javadoc-plugin/javadoc-mojo.html#source

Just set that to 8.  I've been able to release with java 14 no problems as long as javadocs still think they are targetting 8.  Codes bases I work with target anywhere from 7 to 14 currently.  That seemed to help me get past issues.  In fact, you can run the javadoc plugin on it's own and the failure you have currently should still show up without going through release.  That switch it will work again and stop the complaints on modular as it won't look for that.

**Comment by dbwiddis** [comment]
Added `<source>8</source>`.  New error. Building with jdk13.

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:javadoc (default-cli) on project oshi-core: An error has occurred in Javadoc report generation: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses packages in the unnamed module, but the packages defined in https://docs.oracle.com/en/java/javase/13/docs/api/ are in named modules.
```

**Comment by hazendaz** [comment]
How about jdk 14?  Any difference there?  I recall seeing that and probably had something else I did.  I'll have to look tomorrow if jdk 14 doesn't resolve it.  In my case, I've been using oracles jdks.

**Comment by dbwiddis** [comment]
For which googling the bug [leads here](https://bugs.openjdk.java.net/browse/JDK-8212233), which tells me to add `<source>8</source>` to fix it, when that's what caused it. :D 

JDK14 isn't easy for me, I'm using homebrew and they are [stuck on 13](https://discourse.brew.sh/t/will-openjdk-14-be-added-to-the-java-package/7216).  I'll keep playing with easy fixes but this is very low on my list right now...

**Comment by dbwiddis** [comment]
Found `<detectJavaApiLink>false</detectJavaApiLink>` from [this SO link](https://stackoverflow.com/questions/58836862/jdk-11-and-javadoc) and that works with `javadoc:javadoc`....

**Comment by hazendaz** [comment]
Yah a couple teams that were having same issue used that to get around it.  I was able to do so without it.  Not sure why.  I'm actually logging into work now to see what I did.  Possibly that helps with openjdk not sure.

**Comment by hazendaz** [comment]
Only other thing I had which is probably not related was to have <additionalOptions>-html5</additionalOptions> set.  The source was the only other one I had set and I had noted a comment that it seemed to affect the 'test' code rather tha source code in my case.  More broadly I stopped using the older compiler options for the jdk and only use release but that has some other side effects like m2e not respectiing the java version and sonar not yet supporting the newer 'release' tag either.  It's definitely a combination of things for sure.

**Comment by dbwiddis** [comment]
Well, looks like that last bit did the magic.  4.9.0 made it to staging. :)   Thanks for the help.  Now you can add me to the list of examples to point people to when this inevitably happens.

**Comment by dbwiddis** [comment]
But, not out of the woods yet.  Failed javadoc validation.

typeId | javadoc-staging
-- | --
failureMessage | Missing: no javadoc jar found in folder '/com/github/oshi/oshi-core-shaded/4.9.0'

So perhaps I now need to remove that `<sourcepath>`.   Ugh.

**Comment by dbwiddis** [comment]
Annnd, nope.  Removing sourcepath on the shaded jar brings back the same error as before.  Perhaps it's configured wrong.  In any case, a problem for tomorrow.

**Comment by dbwiddis** [comment]
Tried a few more `<sourcepath>` varations without success.   I think the correct answer is to use the `build-helper-maven-plugin` to copy something over from `oshi-core` to `oshi-core-shaded` but I'm not sure if I need the sources or the compiled javadocs or just to set a property/parameter.  I'm prepared to buy a beverage of choice for someone who can help me fix this. :)

**Comment by dbwiddis** [comment]
Still haven't solved this, but I think I at least have found the problem.  Last line is relevant... :)
```
    [INFO] --- maven-shade-plugin:3.2.4:shade (default) @ oshi-core-shaded ---
    [INFO] Including org.slf4j:slf4j-jdk14:jar:1.7.30 in the shaded jar.
    [INFO] Including org.slf4j:slf4j-api:jar:1.7.30 in the shaded jar.
    [INFO] Excluding com.github.oshi:oshi-core:jar:4.9.0 from the shaded jar.
```

**Comment by hazendaz** [comment]
Would that be because of inclusion of shading being only for logging?  Not sure personally what the value is of shading to start with.  What is the intent of that module?

**Comment by hazendaz** [comment]
If only to have a single JAR for usage, why not just make it a spring boot jar?

**Comment by dbwiddis** [comment]
Meh, nevermind, that's not the problem.  It also excluded JNA. There are specific includes for slf4j for some reason.

**Comment by dbwiddis** [comment]
I'm poring over [the docs here](https://maven.apache.org/plugins/maven-javadoc-plugin/examples/aggregate-dependency-sources.html) looking for what I may be missing.

**Comment by dbwiddis** [comment]
Well, I give up.  Rolled back to 3.1.1.  These work for the upgrade to automatic module name:
						<source>8</source>
						<detectLinks>true</detectLinks>
						<detectJavaApiLink>false</detectJavaApiLink>

But trying to use javadoc 3.2.0 even with these settings gives the error in the original post; overriding "sourcepath" lets it compile for tests, but fails to produce javadocs for the shaded jar, which prevents me from making a release from Central.

So the final step for 3.2.0 is probably something to do with the sourcepath or other means of telling the shaded jar where to find the javadocs, but it's not obviously documented.

**Comment by dbwiddis** [comment]
Hey, @raphw, any chance you can elaborate on what you did to [solve this SO question](https://stackoverflow.com/questions/23563857/including-a-synthetic-file-as-javadoc-artifact-in-a-maven-build/24552618#comment110666631_24552618)? :)

[![image](https://user-images.githubusercontent.com/9291703/85872527-bb0d5280-b784-11ea-895f-814f5d77f8c6.png)](https://xkcd.com/979/)

**Comment by raphw** [comment]
I don't think those are releated. The SO answer adresses the OP need to download a jar file to a given location to include it in the release artifact.

The problem you are facing seems like you have modules in your dependencies (which get resolved by the javadoc tool) which define inconsistent module relationships. It's surprising this problem surfaces when you are using Java 8 rather then Java 11.

Accoring to the error messages your modules `com.github.oshi.demo` and `com.github.oshi` define a so-called split-package, i.e. define types in the same named package what is not allowed when using modules. I assume the javadoc plugin detects this problem. Are you shading your core module into demo? If you do so and define both as a module and then create a compound javadoc of both, this will create invalid (automatic) modules and probably lets the plugin fail.

**Comment by dbwiddis** [comment]
The `oshi-demo` artifact/module shouldn't even be seen by the shaded-jar, it only has a dependency on `oshi-core`.  The split-module errors you are seeing were resolved by using `<source>8</source>`.

I'm back to the original problem at the top of this thread, namely:
* with default settings in the `oshi-core-shaded` pom, the javadocs are generated, but I get "Error while generating Javadoc: ...  Error reading file: /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/../apidocs/element-list"
* I can make that error go away by setting `<sourcepath>anything</sourcepath>` but in this case, no javadocs are generated.

I am pursuing one of two possible solutions:
* set the `<sourcepath>` and download the javadoc files generated from `oshi-core` into the `oshi-core-shaded` project.  This is why your SO post seemed relevant.  Or
* Figure out the correct value to set `<sourcepath>` to.

**Comment by raphw** [comment]
I see. I think the shade plugin and javadoc plugins are not playing nicely. Does the error occur if you add a single "original" class to your shaded Maven artifact (into the source folder)?

**Comment by dbwiddis** [comment]
Seems like a reasonable suggestion.  I'll give it a shot next release.  In the meantime, I am curious how you copied javadocs over using the resource plugin. :)

**Comment by raphw** [comment]
In the linked issue, the jar is copied from the other module to the shaded module to replace the otherwise missing javadoc file. I don't think that's the problem in your case, though since a target javadoc can be found.

**Comment by dbwiddis** [comment]
Tried to do a modular release using 3.2.0 with a `<source>` other than 8, but encountered errors.   The previously mentioned `<sourcePath>` was necessary.

So this worked to release just `oshi-core`:
```
<source>8</source>
<sourcepath>src/main/java</sourcepath>
<detectLinks>true</detectLinks> <!-- don't think it's needed but doesn't hurt -->
<detectJavaApiLink>false</detectJavaApiLink>
```
I think, reading back, this mostly worked with the shaded jar, other than that `oshi-core-shaded` couldn't find any javadocs.   I suspect there's a solution down that road playing with `<sourcepath>` configured specifically for the shaded artifact to look elsewhere.

**Comment by dornand** [comment]
A little bit off-topic, but do you think it's worth it, to get rid of the 'dangling' javadoc file headers?
Could save some trouble with javadoc tools in general.

The license-maven-plugin already changed their default comment format for the next version:
[license headers for java files #118](https://github.com/mycila/license-maven-plugin/issues/118)

**Comment by dbwiddis** [comment]
If it were closer to the end of the year, I'd say make the change with the annual year update.  But now?  Probably wouldn't mind it, but also not a big priority for me.

What I would really like is for some magic to prevent the XML license header from reformatting itself when I edit pom.xml!. :grin:

**Comment by hazendaz** [comment]
@dbwiddis license plugin rc resolves the javadoc issue.  It works as is, just don't go using their new format just yet as that is buggy still.  It's a pretty heavy hit the first time but fixes the javadoc consideration.  As to the pom, depends what is causing that situation.  I've seen it happen many times but its usually caused by running a formatter separately in an IDE.  In the real rare case it happens just because (not sure why).  But maybe less on the latest license plugin.  I had worked on the more recent rc for that and have been using it in production since, seems better in general.

**Comment by dbwiddis** [comment]
The pom isn't actually the plugin, it's my Eclipse formatter.  I was mostly lamenting the lack of a `/*-` equivalent for XML comments.  TBH, I don't really see a need for license headers in the POM anyway, I doubt anything in there is copyrightable.  Perhaps when we do the mass upgrade I'll remove those as part of the "touch every file" commit.

Given it's in rc stage I'm content to wait for the official release and then just do a mass change.

**Comment by dbwiddis** [comment]
And, nope.  Still fails on 3.2.0 even with a source path pointing to oshi-core.
```
    [INFO] No previous run data found, generating javadoc.
    [INFO] 
    Loading source file /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/../oshi-core/src/main/java/oshi/hardware/CentralProcessor.java...
```
... loaded all the source files from `oshi-core` source directory
```
    Constructing Javadoc information...
    Standard Doclet version 15.0.1+9
    Building tree for all the packages and classes...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/oshi/driver/unix/aix/Ls.html...
```
... Generated html in `oshi-core-shaded/target/apidocs`
```
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/overview-tree.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/deprecated-list.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/index.html...
    Building index for all the packages and classes...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/index-all.html...
    Building index for all classes...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/allclasses-index.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/allpackages-index.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/overview-summary.html...
    Generating /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/help-doc.html...
    1 error
```
And chokes:
```
    [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (javadoc-jar) on project oshi-core-shaded: MavenReportException: Error while generating Javadoc: 
    [ERROR] Exit code: 1 - javadoc: error - Error reading file: /Users/danielwiddis/git/oshi/target/checkout/oshi-core-shaded/target/apidocs/../apidocs/element-list
```
So I guess it's back to 3.1.1.

**Comment by dbwiddis** [comment]
For the record, attempted a release today with 3.3.0 and got the same symptoms.  Rolling back to 3.1.1 (again).

**Comment by mprins** [comment]
> For the record, attempted a release today with 3.3.0 and got the same symptoms. Rolling back to 3.1.1 (again).

didn't see this... reverting #1652

**Comment by dbwiddis** [comment]
Well, JNA 5.9.0 came out so I attempted a release today and hit a new problem:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.9.1:site (default-site) on project oshi-core: Error generating maven-javadoc-plugin:3.1.1:aggregate-no-fork report: 
> [ERROR] Exit code: 1 - /Users/danielwiddis/git/oshi/oshi-core/src/main/java/oshi/hardware/platform/mac/MacComputerSystem.java:31: error: package com.sun.jna does not exist
> [ERROR] import com.sun.jna.Native; 

This occurs during the `mvn site` step.  It looks like it may be a manifestation of https://issues.apache.org/jira/browse/MJAVADOC-609 which also points to https://issues.apache.org/jira/browse/MJAVADOC-620 as a root cause, but these were allegedly fixed in 3.2.0.

But I tried with 3.3.0 and the same issue.  I tried rolling back to the previous release state and the same issue.

Only thing that I think changed is my jdk version (building with 16.0.2).   Guess I'll try an earlier version there....

**Comment by dbwiddis** [comment]
For the record, was a bit bored and decided to try again with 3.3.1.  Still doesn't work.  Summary:
 - `<source>8</source>` doesn't really help
 - `<detectJavaApiLink>false</detectJavaApiLink>` doesn't really help
 - `<sourcepath>../oshi-core/src/main/java</sourcepath>` is necessary to actually build the javadocs (otherwise the release appears to work but fails ossrh validation with no javadocs), but the path generated looking for `element-list` doesn't appear to use this setting, so that's the most likely cause that needs investigating.

**Comment by hazendaz** [comment]
on the bright side, maven has a lot of steam going now.  I'm still having issues with javadocs with newer builds myself - they were last blaming oracle but how knows for sure (I downgrade all to source 8 on purpose which loves my 'var' usage).  My fingers are crossed as a lot of new blood in maven committers and they are moving fast.  Some of that will be hit or miss but its going right direction so there is hope :)

**Comment by dbwiddis** [comment]
Yeah, but I'm starting to lose hope on this one.  I know nobody's going to try to fix it based on only the info I have and everyone will want a minimal reproducer.  But given that I have to actually publish to OSSRH to reproduce it's not really that easy to do!  (Yeah I'm sure there's some other maven command that will reproduce "the problem" but I haven't had the time to dig into it.)

Ironically I think I know the exact commit with the problem (look up to the top of the thread) but really don't know enough to figure out what's happening.

**Comment by hazendaz** [comment]
osgi is something that can be used on any module.  The shaded module claims in FAQ that is reason for it but it IMHO isn't doing setup correctly as it is forcing slf4j partially with same named path and I'm pretty sure OSGI would be looking for the artifact that is maching (its shaded so its no longer the same) plus there are a lot of warnings building it.  Now to be far, I don't know OGSI that well other than Eclipse proves it barely works properly with conflicts everywhere.  Modules were the replacement but regardless, if you want to shade stuff internally like that it should all be shared not just part of it.  And I don't think suggestion of slfj4-jdk14 makes any rational sense.  That is legacy java logging.  13 years of java, I've never seen anyone use javas logger like that because well its horrible.  And the exact reason everyone is using slf4j or log4j2.  Its late, maybe going a bit mad here...what am I missing on the need for that module?

**Comment by dbwiddis** [comment]
I would defer to @swimmesberger (#375 and #605) and @lprimak (#464) on the OSGi / shaded JAR questions.  Perhaps that should be a new issue.  As for usage, we had 1175 downloads of it from the central repository last month and it's still more popular than the JPMS artifact.

**Comment by dbwiddis** [comment]
I was able to successfully prepare a release (including passing all checks at OSSRH, one click away from a true release) with the latest `maven-javadoc-plugin` version (3.3.1) by doing exactly one change in the pom:

Removing the automatic module name.

This suggests a few possible fixes that I'll attempt shortly:
 - Having a per-module automatic module name, just in case there's an issue using the same one as the shaded dependency
 - Overwriting the manifest section in the config in the shaded jar, without an automatic module name.  That will keep it on the main project but hopefully let the shaded jar build proceed normally.

**Comment by lprimak** [comment]
Thanks @dbwiddis , shaded JAR is not my core competency here, I just fixed the OSGi issue, which is unrelated

**Comment by dbwiddis** [comment]
Thanks @lprimak -- what OSGi issue did you fix?  I'm not seeing a PR?

**Comment by lprimak** [comment]
#464

**Comment by dbwiddis** [comment]
Ah, gotcha.  You still know more about it than I do! Heh.  I think the bigger question is -- are you still using it?

**Comment by lprimak** [comment]
I’m not sure to be honest. Probably an older version

**Comment by dbwiddis** [comment]
OK, so we're finally closing this 2-year-old issue. 🥳 🎆 🍾 

When a module creating a shaded JAR using `maven-shade-plugin` has a manifest in `maven-jar-plugin` that includes an Automatic Module Name, the `maven-javadoc-plugin` fails (since 3.2.0).

Fixed in #1866 by using inheritance with appending for the manifest, and only including the Automatic Module Name in the `oshi-core` artifact, so the module creating the shaded jar is blissfully ignorant of modules.

Not sure whether to file a bug at maven-javadoc-plugin site for this, as it's really a corner edge case that is easily (now that I know why) worked around and ultimately is probably a user configuration issue as the shaded jar shouldn't have a module name anyway.   Tagging @olamy for info, in case anyone else runs into this!

**Comment by dbwiddis** [comment]
Eh.  Not so fast.  Looked good deploying but no javadocs generated.  It seems the problem may be with the shaded jar using the just-generated oshi-core jar with the automatic module name in the manifest.

So I think the correct solution is just to eliminate the automatic module name... and this is probably a bug that needs reporting, although I'm doubtful I'll be able to create a minimal reproducer. :(

**Comment by dbwiddis** [comment]
And a few hours later, I'm no better than when I started.  I have no idea what I did the first time that made it work; it doesn't work any more.   ARGH.

**Comment by dbwiddis** [comment]
Circling back... the shaded jar was added in #465 by @lprimak with the reasoning that OSGi couldn't use the regular artifact due to something about slf4j.  But looking around elsewhere i don't see this as a constraint anywhere.

**Comment by dbwiddis** [comment]
OK... the original requestor of the shaded jar doesn't use it any more.  I only found one dependency "in the wild" that imports the dependency and they're still on 5.3.6. 

I think there's a bug somewhere in the javadoc plugin but it's obscure enough that I'm not going to find it and I've wasted too many hours on this.

I'm going to merge #1866 because it's a good idea anyway, and then delete the shaded jar configuration.  If someone needs it, they can add it back, properly set up.
