### ISSUE TITLE
Incorrect CPU usage reported for Windows based processor group setup

### ISSUE THREAD

**Issue by RajeshPutta87** [oshi/oshi#1361]
I am from AppDynamics. We are using OSHI 5.1.0 to retrieve CPU, Memory, Processor, Process information and the environment in use is name=Windows, release=Microsoft Windows Server 2016 Standard, architecture=64-bit

Environment in test is having
64 physical cores
128 logical cores/logical processors

AppDynamics customer had created two processor groups, each with 64 logical processor. Issue is that using OSHI we are detecting CPU activity on the first “processor group”, i.e. 64 logical processors. Generally a instance of a service in run in each processor group – so that means service instances are running in each of the two processor groups on this machine… but OSHI is computing CPU activity on only one processor group.

Attached are the results of client's testing of the 64 core issue…  the first screenshot shows the CPU usage (57%) for a task that ran on the second processor group  (cores 64 – 127) for about 1.5 minutes from 3:45pm to 3:47pm.
The second screenshot shows the CPU usage (also 57%) for the same task run on the first processor group (cores 0 – 63) also for about 1.5 minutes from 4:00p to 4:02pm.

The third screenshot show the AppDynamics using OSHI shows a max cpu trend from 3:40pm to 4:04pm and doesn't correctly reflect the CPU usage.

I also referred to https://github.com/oshi/oshi/issues/785. This looks to be relevant to this issue.

![image009](https://user-images.githubusercontent.com/72386265/96132255-cfce4b80-0f17-11eb-826b-461d0912d2e0.jpg)

Can you please look into the issue.

![image007](https://user-images.githubusercontent.com/72386265/96132078-939aeb00-0f17-11eb-9435-505328caa22a.png)
![image008](https://user-images.githubusercontent.com/72386265/96132111-9bf32600-0f17-11eb-9a86-236cc9ae1899.png)

Thanks
Rajesh

**Comment by RajeshPutta87** [comment]
[Uploading processor.txt…]()

**Comment by RajeshPutta87** [comment]
[processor.txt](https://github.com/oshi/oshi/files/5385334/processor.txt)

**Comment by dbwiddis** [comment]
To troubleshoot this more I'll probably need some information from the relevant machine.  Will it be possible to do so?  I'd need ideally both, but at least one of:
 - a view of the performance counters for "Processor Information", specifically the format of the instances which should identify the processor groups uniquely
 - output of the query `wmic path Win32_PerfRawData_Counters_ProcessorInformation`

**Comment by dbwiddis** [comment]
To clarify the above request, I can really only see two possibilities for this issue.  The code-based assumption regards the interaction between processor groups and NUMA nodes and the performance counter instance name.

The map which correlates perfmon instance to logical processor assumes a comma-delimited name (e.g., on my machine with only one processor group/numa node, my 8 logical processors are `0,0`, `0,1`, ..., `0,7`) in which the first digit is the NUMA node.  So in the case of this machine if there are 4 NUMA nodes (one for each socket) these would be `0,0` thru `0,31`, `1,0` thru `1,31`, `2,0` thru `2,31`, and `3,0` thru `3.31`.  Missing half of those indicates possibly the first digit is the processor group and the instance names are `0,0` thru `0,63` and `1,0` thru `1,63`.

The other possible explanation is which perfmon counters OSHI (or any process in one processor group) would have access to.  If the instances are correctly returning the different NUMA nodes but half the counter values are 0, that would indicate an inability to collect that information.  This shortcoming is explicitly documented for CPU Frequency information, for example, but it wouldn't surprise me if there's a similar issue for CPU usage.

So, for the above request, the key information needed is the format of the instances (and do they go 0-1 or 0-3 for the first digit) and whether there are sensible values in the data.

**Comment by dbwiddis** [comment]
Aha... the same problematic iteration in #1360 could also be the culprit here!  The core bitmasks are iterated here:
```
for (int i = lowBit; i <= hiBit; i++) {
```
And the value `i` is assigned to the processor number.  With 4 cores, the second iteration may be going 32-63 (or 62 per the other bug!) for processor numbers, creating map key `1,32` instead of `1,0`. 

So a list of instance names from 2 comments up will confirm this and I can fix it.

**Comment by dbwiddis** [comment]
Actually the fix is a bit more involved for #1360.  Please add changelog and fix the title here, I'll merge it. If you're interested in fixing #1360 as well, let me know.

**Comment by RajeshPutta87** [comment]
@dbwiddis I have modifed as per recommendations in https://github.com/oshi/oshi/issues/1360. Please let me know if those changes helps here or do you still need information as updated in your first update

Thanks
Rajesh

**Comment by dbwiddis** [comment]
OK, I'm pretty sure I've tracked down the root cause of this, but since I don't have a system to test on, I'm going to need some instrumentation of a machine like the one reported in order to figure out the correct fix.

The problem is somewhere in [getLogicalProcessorInformationEx()](https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java#L57).

For each processor, bitmask information is added to a list of packages, NUMA nodes, and cores.   Then, starting  at line 91, logical processor numbers are assigned based on that bitmask. 

The problem is I'm not sure what those bitmasks really are, if they reset to 0 per NUMA node or per processor group. 

I'm pretty sure the hardcoded `groupMask[0]` on line 75 is the problem, but I'm not yet sure the best way to fix it.

Ideally someone could instrument this method and provide output printing out the summarizing the `LOGICAL_PROCESSOR_RELATIONSHIP` values in the loop starting at line 66, particularly the index (`i`), relationship (`procInfo[i].relationship`), and the array of `procInfo[i].groupMask` values (`procInfo[i].groupCount` gives the size of the array).

**Comment by dbwiddis** [comment]
The fix recommended in #1360 actually needs to be applied 5 places.  See #1362 for specific methods... but just search for `1 << lp` and replace the `> 0` with `!= 0` for each.  That only fixes the "missing processor 63" problem, though.   This fix is more nuanced... I expect the bitmasks are assuming numbering `0,0` thru `0,63` and `1,0` thru `1,63` while performance counters are using NUMA nodes for each core, and going only up to 31 for each of 4 nodes.  So the perf counter instance numbers are still needed. as well as the `LOGICAL_PROCESSOR_RELATIONSHIP` data in the previous comment. Between these two bits of data I can fix this.

**Comment by dbwiddis** [comment]
Summary of desired information:
1. Either a list or description of the "instance names" for processor perf counters.  These can be found by running `perfmon.exe` and looking at the `Processor Information` counters.   I need to know if they go from `0,0` to `1,63` in groups of 64, or from `0,0` to `3,31` in groups of 32.
2. Data from `SYSTEM_LOGICAL_PROCSSOR_INFORMATION_EX` values.  Please add the following debug code to `LogicalProcessorInformation.getLogicalProcessorInformationEx()` inside the loop on line 66:
```
        for (int i = 0; i < procInfo.length; i++) {
            int groupCount = ((PROCESSOR_RELATIONSHIP) procInfo[i]).groupCount;
            long[] mask = new long[groupCount];
            GROUP_AFFINITY[] groupMask = ((PROCESSOR_RELATIONSHIP) procInfo[i]).groupMask;
            StringBuilder affinity = new StringBuilder();
            for (GROUP_AFFINITY aff : groupMask) {
                affinity.append("group=").append(aff.group);
                affinity.append(", mask=").append(Long.toBinaryString(aff.mask.longValue()));
                affinity.append(". ");
            }
            System.out.format("i = %d, relationship = %d, groupCount = %d, bitmasks: %s%n", i,
                    procInfo[i].relationship,
                    groupCount, affinity.toString());
            // rest of loop
          }
```

**Comment by dbwiddis** [comment]
Actually that code crashes....let me rewrite the debug.

**Comment by dbwiddis** [comment]
```
public static debug() {
        // Collect a list of logical processors on each physical core and
        // package. These will be 64-bit bitmasks.
        SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX[] procInfo = Kernel32Util
                .getLogicalProcessorInformationEx(WinNT.LOGICAL_PROCESSOR_RELATIONSHIP.RelationAll);
        StringBuilder affinity = new StringBuilder();
        for (int i = 0; i < procInfo.length; i++) {
            GROUP_AFFINITY aff;
            switch (procInfo[i].relationship) {
            case LOGICAL_PROCESSOR_RELATIONSHIP.RelationProcessorPackage:
                GROUP_AFFINITY[] affs = ((PROCESSOR_RELATIONSHIP) procInfo[i]).groupMask;
                affinity.append("package");
                for (GROUP_AFFINITY gaff : affs) {
                    affinity.append(", group=").append(gaff.group);
                    affinity.append(", mask=").append(Long.toBinaryString(gaff.mask.longValue()));
                    affinity.append(". ");
                }
                break;
            case LOGICAL_PROCESSOR_RELATIONSHIP.RelationNumaNode:
                aff = ((NUMA_NODE_RELATIONSHIP) procInfo[i]).groupMask;
                affinity.append("node=").append(aff.group);
                affinity.append(", mask=").append(Long.toBinaryString(aff.mask.longValue()));
                affinity.append(". ");
                break;
            case LOGICAL_PROCESSOR_RELATIONSHIP.RelationProcessorCore:
                int groupCount = ((PROCESSOR_RELATIONSHIP) procInfo[i]).groupCount;
                GROUP_AFFINITY[] groupMask = ((PROCESSOR_RELATIONSHIP) procInfo[i]).groupMask;
                for (GROUP_AFFINITY gaff : groupMask) {
                    affinity.append("group=").append(gaff.group);
                    affinity.append(", mask=").append(Long.toBinaryString(gaff.mask.longValue()));
                    affinity.append(". ");
                }
                break;
            default:
                // Ignore Group and Cache info
                break;
            }
            System.out.format("i = %d, relationship = %d, bitmasks: %s%n", i,
                    procInfo[i].relationship,
                    affinity.toString());
        }
    }

**Comment by dbwiddis** [comment]
I've pushed a fix that I think solves this issue in #1363.  Can you test the current SNAPSHOT to see if it resolves the problem? 

If so, I'll make a release.

**Comment by RajeshPutta87** [comment]
Hi Daniel,

I have created a SNAPSHOT for the changes you have made and shared it with my customer. I will keep you updated once customer shares the observations. Hoping that it will address both #1360 and #1361

Thanks
Rajesh

**Comment by dbwiddis** [comment]
I've gone ahead and release 5.3.1 with these changes, as I'm fairly confident this should fix the problem.

I'll close this issue; if this does not resolve the problem, feel free to reopen it or create a new issue.

**Comment by RajeshPutta87** [comment]
Hi Daniel,

We have validated and could see the incorrect logical processor issue (https://github.com/oshi/oshi/issues/1360) is solved. We could see correct 128 logical processor count). 

But the incorrect CPU usage issue which was logged as part of this issue https://github.com/oshi/oshi/issues/1361 is still not yet solved. CPU usage is detected on only half the cores. Can you please look into it.

I have attached jar file here. I have changed extension jar to txt for your reference
[oshi-core-5.1.0.txt](https://github.com/oshi/oshi/files/5419777/oshi-core-5.1.0.txt)

Please let me know in case you need any specific details.

Thanks
Rajesh

**Comment by dbwiddis** [comment]
Unfortunately the jar file isn't any help, as it's just the compiled classes.  As I do not have a machine with more than 64 processors to test on, it's very difficult to debug further, as I am relying solely on documentation.  

I would reopen this issue but since you have opened another issue I'll continue to track there.
