### ISSUE TITLE
2 warnings from SLF4J: Disabling further attempts to query PhysicalDisk + WmiQueryHandler COM exception: Invalid Class

### ISSUE THREAD

**Issue by minduch** [oshi/oshi#1811]
The following warnings are logged using SLF4J:

- OSHI-core 5.8.5
- JNA (jna and jna-platform) version 5.10.0
- Windows 11, ver = Microsoft Windows [Version 10.0.22000.348]
- 1 NVMe SSD, 1 HDD, 1 SSD
- Java 11 Update 3 Eclipse Temurin, 64 bit

1.
<oshi.util.platform.windows.PerfCounterWildcardQuery>  [Worker-8: Executing the early startup extensions,5,Equinox Event Admin]  Disabling further attempts to query PhysicalDisk.
```
	at oshi.util.platform.windows.PerfCounterWildcardQuery.queryInstancesAndValues(PerfCounterWildcardQuery.java:92)
	at oshi.driver.windows.perfmon.PhysicalDisk.queryDiskCounters(PhysicalDisk.java:79)
	at oshi.hardware.platform.windows.WindowsHWDiskStore.queryReadWriteStats(WindowsHWDiskStore.java:243)
	at oshi.hardware.platform.windows.WindowsHWDiskStore.getDisks(WindowsHWDiskStore.java:180)
	at oshi.hardware.platform.windows.WindowsHardwareAbstractionLayer.getDiskStores(WindowsHardwareAbstractionLayer.java:76)
```

2.
<oshi.util.platform.windows.WmiQueryHandler>  [Thread-31,3,main]  COM exception: Invalid Class Win32_PerfRawData_PerfDisk_PhysicalDisk WHERE NOT Name="_Total"
```
	at oshi.util.platform.windows.WmiQueryHandler.queryWMI(WmiQueryHandler.java:166)
	at oshi.util.platform.windows.WmiQueryHandler.queryWMI(WmiQueryHandler.java:127)
	at oshi.util.platform.windows.PerfCounterWildcardQuery.queryInstancesAndValuesFromWMI(PerfCounterWildcardQuery.java:194)
```

**Comment by dbwiddis** [comment]
This is one of the reasons I want more WMI driver query tests written in #1727 ...

Firstly, this is a "fallback" backup query when you have a problem with the performance counters, where it is trying to read the PhysicalDisk counter.   In theory it should never get to WMI.   But now that it has, the query is indeed broken.
```
WHERE NOT Name="_Total"
```
should be
```
WHERE Name !="_Total"
```
I suspect this is not the only broken query of this sort.

**Comment by dbwiddis** [comment]
Note: I'm working on a PR in #1812 to test all the WMI things, and there are bigger issues than this bug.  If it's urgent to fix this bug I can do it quickly but I'm hoping to dig into the deeper issues. I'm planning on a release with a fix by this coming weekend.

The underlying problem with the "primary" data source can probably be fixed by rebuilding performance counters.

**Comment by minduch** [comment]
For me it's fine - we can wait. Better to have a good new version around next week on Maven Central.

**Comment by minduch** [comment]
FYI: This is still an issue in oshi-core-[java11]-6.1.4 - that is sad, although the warning messages are a little different now:
```
Disabling further attempts to query PhysicalDisk.
```
and
```
COM exception: Invalid Class Win32_PerfRawData_PerfDisk_PhysicalDisk WHERE Name!="_Total"
```
Now using Java 11.0.14.1 on Windows 11 Version 10.0.22000.556.

**Comment by dbwiddis** [comment]
Can you test this on the command line and tell me what happens?
```
wmic path Win32_PerfRawData_PerfDisk_PhysicalDisk
```
Can you run `perfmon.exe` and try to add a counter for "PhysicalDisk" ?

![image](https://user-images.githubusercontent.com/9291703/158086353-3d76eacf-2d98-4c50-9225-2d6fd596e109.png)

**Comment by dbwiddis** [comment]
Also check your registry: make sure this is not set to 1. If it is, set to 0.
> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Perfdisk\Performance\Disable Performance Counters

**Comment by minduch** [comment]
Hi Daniel,

The DWORD value is set to 4 (not 0 or 1). What does it do?

/Christopher

**Comment by dbwiddis** [comment]
> The DWORD value is set to 4 (not 0 or 1). What does it do?

According to [this site](https://leansentry.zendesk.com/hc/en-us/articles/360038645792-How-to-Fix-performance-counter-issues)
> Set "Disable Performance Counters" to 0. Any value other than 0 causes the performance counter to be disabled

**Comment by minduch** [comment]
The commands

  1.  net stop pla
  2.  net start pla
requires Admin to run. Access denied (5) otherwise.

**Comment by minduch** [comment]
Hi Daniel,

First I get from CMD.EXE:

wmic path Win32_PerfRawData_PerfDisk_PhysicalDisk
Node - SPACY
ERROR:
Description = Invalid class

that seems to match what OSHI says.

Running Perfmon shows warning dialog box directly:

***@***.***

Sorry I can’t resize the dialog box to get the other errors. Even when running as Administrator. This is how the Resource Monitor window looks like:

***@***.***

Or as admin:

***@***.***

Registry changed DWORD from 4 to zero, new warning message:

***@***.***

Perfmon main window, localhost:

***@***.***

Perfmon for \\FREJA<file://FREJA> a Windows 2019 server (I am admin on it):

***@***.***

Now that I changed the DWORD registry value from 4 to zero (0), it says (both in CMD and Powershell):

From CMD (nicely formatted, as normal user, no elevation to admin):

wmic path Win32_PerfRawData_PerfDisk_PhysicalDisk
AvgDiskBytesPerRead  AvgDiskBytesPerRead_Base  AvgDiskBytesPerTransfer  AvgDiskBytesPerTransfer_Base  AvgDiskBytesPerWrite  AvgDiskBytesPerWrite_Base  AvgDiskQueueLength  AvgDiskReadQueueLength  AvgDisksecPerRead  AvgDisksecPerRead_Base  AvgDisksecPerTransfer  AvgDisksecPerTransfer_Base  AvgDisksecPerWrite  AvgDisksecPerWrite_Base  AvgDiskWriteQueueLength  Caption  CurrentDiskQueueLength  Description  DiskBytesPersec  DiskReadBytesPersec  DiskReadsPersec  DiskTransfersPersec  DiskWriteBytesPersec  DiskWritesPersec  Frequency_Object  Frequency_PerfTime  Frequency_Sys100NS  Name    PercentDiskReadTime  PercentDiskReadTime_Base  PercentDiskTime  PercentDiskTime_Base  PercentDiskWriteTime  PercentDiskWriteTime_Base  PercentIdleTime  PercentIdleTime_Base  SplitIOPerSec  Timestamp_Object  Timestamp_PerfTime  Timestamp_Sys100NS
11150005248          431396                    15183207424              676393                        4033202176            244997                     1624772828          1221616663              1221616663         431396                  1624772828             676393                      403156165           244997                   403156165                         0                                    15183207424      11150005248          431396           676393               4033202176            244997            0                 10000000            10000000            0 C:    1221616663           132917018761289960        1624772828       132917018761289960    403156165             132917018761289960         37150142850      132917018761289960    15143          0                 38179842624         132917018761289960
277889024            1074                      278032384                1107                          143360                33                         7767592             7722961                 7722961            1074                    7767592                1107                        44631               33                       44631                             0                                    278032384        277889024            1074             1107                 143360                33                0                 10000000            10000000            1 D:    7722961              132917018761289960        7767592          132917018761289960    44631                 132917018761289960         38067621547      132917018761289960    0              0                 38179842624         132917018761289960
42048000             8519                      44363264                 8772                          2315264               253                        9388117             7695189                 7695189            8519                    9388117                8772                        1692928             253                      1692928                           0                                    44363264         42048000             8519             8772                 2315264               253               0                 10000000            10000000            2 E:    7695189              132917018761289960        9388117          132917018761289960    1692928               132917018761289960         38067880456      132917018761289960    0              0                 38179842624         132917018761289960
11469942272          440989                    15505603072              686272                        4035660800            245283                     1641928537          1237034813              1237034813         440989                  1641928537             686272                      404893724           245283                   404893724                         0                                    15505603072      11469942272          440989           686272               4035660800            245283            0                 10000000            10000000            _Total  412344937            132917018761289960        547309512        132917018761289960    134964574             132917018761289960         37761881617      132917018761289960    15143          0                 38179842624         132917018761289960

Please advise what to do…

**Comment by dbwiddis** [comment]
The email to github stripped the images from whatever you were trying to show.

But changing that registry value appears to have fixed WMI and I'm hopeful it also fixes the perfmon issue.

**Comment by minduch** [comment]
Our code, similar to the one below, and it is quite sad that there should be warnings for performance counters when they are never used.

That is why I am suggesting to have an API, on some level to state that e.g. performance will NOT be retrieved and thus avoiding "low level" OS functions that gets them. It would also make the code below run much faster.

```
    String info; // Used to save the info, not shown below because it has nothing to do with OSHI.

    HardwareAbstractionLayer hw=getSystemInfo().getHardware();
    ComputerSystem cs=hw.getComputerSystem();
    info=cs.getManufacturer();
    info=cs.getModel();
    info=cs.getSerialNumber();
    
    Baseboard bb=cs.getBaseboard();
    info=bb.getVersion();
    
    Firmware fw=cs.getFirmware();
    info=fw.getVersion();
    info=fw.getReleaseDate();
    
    CentralProcessor cp=hw.getProcessor();
    ProcessorIdentifier pi=cp.getProcessorIdentifier();
    info=cp.toString();
    info=pi.getIdentifier();
    info=pi.getProcessorID();
    info=pi.getModel();
    info=Integer.toString(cp.getPhysicalProcessorCount());
    info=Integer.toString(cp.getLogicalProcessorCount());
    
    GlobalMemory mem=hw.getMemory();
    info=Utilities.getEnglishSize(mem.getTotal());
    info=Utilities.getEnglishSize(mem.getAvailable());
    info=Utilities.getEnglishSize(mem.getPageSize());

    OperatingSystem os=_systemInfo.getOperatingSystem();
    info=os.getFamily();
    info=os.getManufacturer();
    info=os.getVersionInfo().getVersion();
    
    for ( NetworkIF nif: hw.getNetworkIFs() )
      {
      info=nif.getMacaddr();
      info=nif.getDisplayName();
      info=nif.getName();
      info=Arrays.toString(nif.getIPv4addr());
      info=Arrays.toString(nif.getIPv6addr());
      info=Long.toString(nif.getMTU());
      info=Long.toString(speed);
      info=Long.toString(nif.getPacketsRecv());
      info=Long.toString(nif.getPacketsSent());
      }
    
    for ( OSFileStore fss: os.getFileSystem() )
      {
      info=fss.getUUID();
      info=fss.getName();
      info=fss.getVolume();
      info=fss.getMount();
      info=fss.getType();
      info=fss.getDescription();
      }
    
    for ( HWDiskStore ds: hw.getDiskStores() )
      {
      info=ds.getSerial();
      info=ds.getName();
      info=ds.getModel();
      info=Utilities.getEnglishSize(ds.getSize());

      for ( HWPartition hwp: ds.getPartitions() )
        {
        info=hwp.getMountPoint();
        info=hwp.getName();
        info=mount;
        info=hwp.getIdentification();
        info=hwp.getType();
        info=hwp.getUuid();
        info=Utilities.getEnglishSize(hwp.getSize()));
        }
      }
```

**Comment by dbwiddis** [comment]
> That is why I am suggesting to have an API, on some level to state that e.g. performance will NOT be retrieved and thus avoiding "low level" OS functions that gets them. 

I'm not clear what you're asking for here.  OSHI gets a LOT of its Windows information from the performance counters -- and they're behind basic Windows programs like the Task Manager.  

I don't know why these are sometimes disabled in the registry. Now that I know where to look I could put investigating those keys into OSHI's logic when they fail so it can provide a more verbose log message.  But we'd still have to decide what to return for the requested data, when the user's machine is configured to not provide it.

**Comment by dbwiddis** [comment]
To be clear, the following information comes from the performance counters on OSHI:
- PerfProc
  - Process stats (priority, elapsed time, memory usage, IO) 
- PerfOS
  - CPU ticks used for CPU usage  
  - Swap file usage and page swaps
  - Context switches
- PerfDisk
  - Disk reads/writes/xfer time

If we don't retrieve that info because the user has them disabled, there's no other way to get it.  The best we can do is tell the user their counters are disabled.

**Comment by dbwiddis** [comment]
Found the Windows docs that explain the 4, it apparently disables 64-bit counters.

https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters

Honestly I think just adding this URL to the log message for any performance counter failures may be a good idea.

**Comment by dbwiddis** [comment]
> Would you mind elaborating a little about how this API would look like?

You'd either set the parameter in the `oshi.properties` file or call `GlobalConfig.set(GlobalConfig.OSHI_OS_WINDOWS_PERFOS_DISABLED, true);` (or similar name; a separate one for OS, Disk, and Proc) immediately upon startup.
- If you intentionally disable it, OSHI will just skip the counters and return sane defaults (probably 0) for those counters with no futher logging.
- If you leave it unset (default) OSHI will test the registry keys to see which ones are disabled in the OS, and log (one time) a helpful warning noting the key it found, and then return the 0's as above with no further logging.
- If you set it false, you'll get the existing behavior (one attempt at performance counters, COM exception afterwards).

> When could this be ready in a new version? I'll test it right away, and we will make sure to quickly implement it.

I'll probably get started on it tonight so you'd at least have a SNAPSHOT to test by tomorrow.

**Comment by minduch** [comment]
@dbwiddis Your solution is fine, although I have a preference for the `GlobalConfig.set(...)` API as we are "code-based" and from the quick look I had on it, there is no good doc about `oshi.properties`, but is is very possible I missed it. Your solution would be perfect! Are there any other things in the SNAPSHOT I should be aware of, in comparison to 6.1.4? Do you publish SNAPSHOT elsewhere (like Maven Central), or are they just on GitHub?

**Comment by dbwiddis** [comment]
The properties file and GlobalConfig class are the same approach.  GlobalConfig loads the properties file but can also be overridden.  The only caveats are that it's not thread-safe, and it doesn't re-read configs, so it should be done as one of the initialization steps.  It's not as trivial to override/replace the properties file in the jar, though, so the programmatic approach tends to be easier to implement.  The properties file itself tends to have a lot more comments about what the settings mean, however, so it's useful on its own.  They're both mentioned in the README under the Usage section.

SNAPSHOT is published after every commit to master at Sonatype's snapshot repository that you can configure in your own POM.  I don't have the syntax to do that handy but here's the URL:  https://oss.sonatype.org/content/repositories/snapshots/com/github/oshi/

I've kept the change log up to date with anything significant since 6.1.4.  Nothing that impacts Windows.

**Comment by minduch** [comment]
@dbwiddis Seems like you have a lot of stuff in the owen! Thank you for the very quick and concise replies. If I can be of help, please let me know, although I am swamped in some 4 to 6 million lines of code to develop and maintain.

**Comment by dbwiddis** [comment]
> If I can be of help, please let me know, although I am swamped in some 4 to 6 million lines of code to develop and maintain.

I'm hoping those millions of lines are skewed heavily toward "maintain" and not "develop" :)

**Comment by dbwiddis** [comment]
Should be fixed in #1974. Still have some documentation to write but I've pushed it to SNAPSHOT from my local branch if you want to test.

**Comment by minduch** [comment]
Thanks! FYI: it works perfectly.

**Comment by dbwiddis** [comment]
Excellent!
